# 统一管理所有需要搜集的账号
scrawler:
  wechat:
    SubscriptionAccounts:
      - 奇点智保
      - 金惠智保
      - 保险师
      - 保险一哥
      - 轻松保严选
      - 慧择保险规划
      - 深蓝保
      - 新一站保险
      - 学霸说保险
      - 蓝鲸insurance
      - 蓝鲸保险之家
      - 保险万事通
      - 今日保
      - 中国保险行业协会
      - 优选保
      - 保险文化
      - 太平洋寿险
      - 太保长航加油站
      - 中国太平洋保险
      - 蓝鲸课堂
      - 沐熙花园
      - 明亚保险经纪
      - 蜗牛保险经纪
      - 关哥说险
      - 饭统戴老板
      - 三折人生
      - 券商中国
      - 英为财情
      - 图解金融
      - 李迅雷金融与投资
      - 越女事务所
      - 也谈钱
      - 大张羽
    max_count: 300
    num_for_once: 15
  bilibili:
    SubscriptionAccounts:
      - name : 二姐聊保障
        id : 353017413
      - name : 明亚保险经纪卢华营
        id : 473336381
      - name : 深蓝保
        id : 454525170
      - name : 深蓝保测评
        id : 702718353
      - name: 圆镜保险insurance
        id: 3546564784031894
      - name: 慧择保险
        id: 487898552
      - name: 白老师保险测评
        id: 3493141451638901
      - name: 一抹地气
        id: 345227902
      - name: 丰险笔记
        id: 445844655
      - name: 精算君Alex
        id: 394070477
      - name: Ginger的保险笔记本
        id: 2087454587
      - name: 阿比Dal
        id: 548088429
      - name: 浪浪历险计
        id: 513517108
      - name: Newman老师_龙博老师
        id: 295438644
      - name: 寿训笔记
        id: 505753530
      - name: 懂保兄弟
        id : 372739961
      - name: 爆肝输出的黄药师
        id : 172292598
      - name: 巫师财经
        id: 472747194
      - name: 小Lin说
        id: 520819684
      - name: 所长林超
        id: 520155988
      - name: 阿牛读财
        id: 477547674
      - name: 复利的奇迹ETF基金理财
        id: 383587023

    # 每次稍微搞一点，否则会被反爬虫
    max_count: 250

downloader:
  wechat:
    # 单次做多下载文章数量
    max_download_size : 120
    # 单次最多额外创建 200 条任务
    max_assign_count: 200
  bilibili:
    # 下载队列当中的文件数量
    max_assign_count: 60
    # 单次最多下载视频数量
    max_download_size: 60
    # 同时下载的视频数量
    batch_size : 4
  zhihu:
    batch_size: 4
