# 统一管理所有需要搜集的账号
scrawler:
  wechat:
    SubscriptionAccounts:
      - 奇点智保
      - 金惠智保
      - 保险师
      - 保险一哥
      - 轻松保严选
      - 慧择保险规划
      - 深蓝保
      - 新一站保险
      - 学霸说保险
      - 蓝鲸insurance
      - 蓝鲸保险之家
      - 保险万事通
      - 今日保
      - 中国保险行业协会
      - 优选保
      - 保险文化
      - 太平洋寿险
      - 太保长航加油站
      - 中国太平洋保险
      - 蓝鲸课堂
      - 沐熙花园
      - 明亚保险经纪
      - 蜗牛保险经纪
      - 关哥说险
    max_count: 300
    num_for_once: 15
  bilibili:
    SubscriptionAccounts:
      - name: 二姐聊保障
        id: 353017413
      - name: 明亚保险经纪卢华营
        id: 473336381
      - name: 深蓝保测评
        id: 702718353
      - name: Ginger的保险笔记本
        id: 2087454587
      - name: 阿比Dal
        id: 548088429
      - name: 浪浪历险计
        id: 513517108
      - name: Newman老师_龙博老师
        id: 295438644
      - name: 寿训笔记
        id: 505753530
    max_count: 300

downloader:
  wechat:
    # 单次做多下载文章数量
    max_download_size : 120
    # 单次最多额外创建 200 条任务
    max_assign_count: 200
  bilibili:
    # 下载队列当中的文件数量
    max_assign_count: 200
    # 单次最多下载视频数量
    max_download_size: 100
    # 同时下载的视频数量
    batch_size : 4
